### PR TITLE
Add ref to How styled-components works

### PR DESCRIPTION
**Pull request by gevgeny**
I have written an article on styled-components. This is in deep explanation of the library under the hood. Hope it is useful.

### CODE REVIEW

**Comment by mxstbr** [comment]
This is awesome! 😍  You should post it in the styled-components community: https://spectrum.chat/styled-components

**Comment by gevgeny** [comment]
Thanks. I will

**Comment by gevgeny** [comment]
@mxstbr Which channel is preferable for sharing articles?

**Comment by mxstbr** [comment]
Just the general one 👍

**Pull request merged**
