### PR TITLE
Add to helpers list with-styled-class-names

### PR DESCRIPTION
**Pull request by RIP21**
Proposal to add this util to the list.
https://github.com/RIP21/with-styled-class-names

Thanks.

### CODE REVIEW

**Comment by philpl** [comment]
Can you add it to the top of the section's list please? :wink:

**Comment by RIP21** [comment]
@philpl with pleasure :)
BTW. New version is coming for styling like react-modal require here.
https://github.com/reactjs/react-modal#using-css-classes
:D A little recursion :)

**Comment by RIP21** [comment]
@philpl any updates? :P

**Comment by philpl** [comment]
We just recently updated the requirements for submission unfortunately :( 

I’m happy to make exceptions but we’ll have to check with @mxstbr

> If you just created something, wait at least 30 days before submitting. This is to give it some time to mature and ensure it's not just a publish-and-forget type of project.

**Comment by RIP21** [comment]
Okay :)
Max said that it's a "good job" :D

https://spectrum.chat/?t=329bf0bc-63eb-4ae9-9ca5-b70fe2947ccc
Proof :D

It's quite tiny, that's why I think its support will be easy :)  As well as the other tiny things that I have in my account. How 30 days will make it any mature, I'm not sure :) I wrote tests! It's proof of my serious intentions :D

**Comment by philpl** [comment]
> Max said that it's a "nice job" :D

Alright, I think you've spent enough time on it to make sure it's "ready" for announcements :wink:

**Comment by RIP21** [comment]
@philpl thanks! I hope it will get a bit more grip and testing after being mentioned here :)

**Pull request merged**
